apiVersion: v1
kind: Service
metadata:
  name: et-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "et-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.collectorPort }}
      targetPort: {{ .Values.service.collectorPort }}
      protocol: TCP
      name: collector
  selector:
    {{- include "et-service.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
