apiVersion: v2
name: srm
description: A Helm chart for SRM
type: application
# This is the chart version. This version should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.2
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
dependencies:
  - name: et-service
    version: 0.4.x
    repository: "file://../et-service"
  - name: et-collector
    version: 0.4.x
    repository: "file://../et-collector"
  - name: et-receiver
    version: 0.4.x
    repository: "file://../et-receiver"
    alias: et-receiver-hit
    condition: enable-receivers
  - name: et-receiver
    version: 0.4.x
    repository: "file://../et-receiver"
    alias: et-receiver-decompile
    condition: enable-receivers
  - name: et-receiver
    version: 0.4.x
    repository: "file://../et-receiver"
    alias: et-receiver-sql
    condition: enable-receivers
  - name: et-receiver
    version: 0.4.x
    repository: "file://../et-receiver"
    alias: et-receiver-agent
    condition: enable-receivers
