enable-receivers: false

et-service:
  image:
    tag: "5.23.2"
  autoscaling:
    enabled: false

et-collector:
  image:
    tag: "5.23.1"
  autoscaling:
    enabled: false

et-receiver-agent:
  image:
    tag: "5.23.2"

et-receiver-decompile:
  image:
    tag: "5.23.2"

et-receiver-hit:
  image:
    tag: "5.23.2"

et-receiver-sql:
  image:
    tag: "5.23.2"
